<?php /** @var $this \Algolia\AlgoliaSearch\Block\Adminhtml\Support\Index */ ?>

<script>
	var algoliaSearchExtentionsVersion = "<?php echo $this->getExtensionVersion(); ?>"
</script>

<div class="legacy_version">
    You’re running version XYZ. Newest available version is ABC. Updating might help fix some issues automatically.
    <a href="https://community.algolia.com/magento/doc/m2/upgrade/" target="_blank">How to update?</a>
</div>

<input type="text" name="q" id="search_box" placeholder="Search for help ..." />

<div>
    <div class="search_results doc">Doc results</div>
    <div class="search_results forum"></div>
</div>

<div class="footer">
    <?php if ($this->isExtensionSupportEnabled()): ?>
        Didn't find what you were looking for?
        <a href="<?php echo $this->getUrl('*/*/contact'); ?>">
            Contact Us.
        </a>
    <?php else: ?>
        Consider <a href="https://www.algolia.com/pricing" target="_blank">upgrading your plan</a>
        to get direct and fast email help by Algolia experts.
    <?php endif; ?>
</div>