<?php /** @var $this Algolia\AlgoliaSearch\Block\Adminhtml\Analytics\DateRange */ ?>
<div class="algolia-analytics-daterange" id="algolia-analytics-daterange">
    <form id="algolia-analytics-daterange-form" data-mage-init='{"validation":{}}' action="<?php echo $this->getFormAction() ?>"  method="post">
        <input type="hidden" name="form_key" value="<?php echo $this->getFormKey() ?>" />
        <div class="inline-field">
            <input type="text" id="analytics_from" name="from"
                   class="admin__control-text input-text date-range-analytics-from"
                   placeholder="<?php echo __('Start Date') ?>" value="<?php echo $this->getFormValue('from') ?>"/>
        </div>
        <span class="divide">-</span>
        <div class="inline-field">
            <input type="text" id="analytics_to" name="to"
                   class="admin__control-text input-text validate-date-range date-range-analytics-to"
                   placeholder="<?php echo __('End Date') ?>" value="<?php echo $this->getFormValue('to') ?>"/>
        </div>
        <button type="submit" class="action submit primary algolia-daterange-submit"><?php echo __('Update') ?></button>
    </form>
</div>

<script type="text/javascript">
    require(["jquery", "mage/calendar", "mage/backend/form"], function($) {
        $('#algolia-analytics-daterange').dateRange({
            dateFormat: "d MMM Y",
            from: {
                id: "analytics_from"
            },
            to: {
                id: "analytics_to"
            }
        });

        var analyticsForm = $('#algolia-analytics-daterange-form').form();
        analyticsForm.on('submit', function(e) {
            e.preventDefault();
            e.stopImmediatePropagation();

            if (analyticsForm.valid()) {
                $.ajax({
                    type: 'post',
                    url: analyticsForm.attr('action'),
                    data: analyticsForm.serialize(),
                    showLoader: true,
                    context: this,
                    dataType: 'json',
                    success: function (response) {
                        if (!response.error) {
                            $('#container').html(response.html_content);
                        } else {
                            alert('An error has occurred. Please try refreshing the page and submitting again.');
                        }
                    }
                });
            }
        });
    });


</script>