<?php /** @var $this \Algolia\AlgoliaSearch\Block\Adminhtml\Analytics\Index */ ?>
<?php if (!$this->checkIsValidDateRange()): ?>
<div class="algoliasearch-notices message message-notice notice">
    <div class="notice">
        <?php echo __('The selected date is out of your analytics retention window (7 days), your data might not be present anymore.'); ?>
    </div>
</div>
<?php endif ?>
<div class="algoliasearch-analytics-overview">
    <div class="row thirds clearfix section">
        <div class="one-third col-1">
            <h4><?php echo __('Total Searches') ?></h4>
            <span class="stat"><?php echo $this->getTotalCount() ?></span>
        </div>
        <div class="one-third col-2">
            <h4><?php echo __('Users') ?></h4>
            <span class="stat"><?php echo $this->getUsers() ?></span>
        </div>
        <div class="one-third col-3">
            <h4><?php echo __('No Results Rate') ?></h4>
            <span class="stat"><?php echo $this->getResultRate() ?></span>
        </div>
    </div>
    <div class="row clearfix section daily-search-section">
        <div class="title">
            <h3><?php echo __('Daily Searches') ?></h3>
            <div class="total-search"><?php echo __('Total Searches') ?> <span class="count"><?php echo $this->getTotalCount() ?></span></div>
        </div>
        <?php $dateCounts = $this->getDateCounts(); ?>
        <?php if (count($dateCounts)): ?>
            <?php foreach ($dateCounts as $daily): ?>
                <div><?php echo $daily['date'] .': '. $daily['count'] ?></div>
            <?php endforeach ?>
        <?php endif ?>
    </div>
    <div class="row halves">
        <div class="one-half section popular-searches">
            <div class="title">
                <h3><?php echo __('Popular Searches') ?></h3>
            </div>
            <div class="analytics-content">
                <?php if (count($this->getTopSearches())): ?>
                    <table class="data-table admin__table-primary">
                        <thead>
                            <tr class="headings">
                                <th><?php echo __('Query') ?></th>
                                <th><?php echo __('Count') ?></th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->getTopSearches() as $search): ?>
                            <tr>
                                <td><?php echo $search['search'] ?></td>
                                <td><?php echo $search['count'] ?></td>
                            </tr>
                        <?php endforeach ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <?php echo __('No searches yet!'); ?>
                <?php endif ?>
            </div>
        </div>
        <div class="one-half section no-result-searches">
            <div class="title">
                <h3><?php echo __('No Result Searches') ?></h3>
            </div>
            <div class="analytics-content">
                <?php if (count($this->getNoResultSearches())): ?>
                    <table class="data-table admin__table-primary">
                        <thead>
                            <tr class="headings">
                                <th><?php echo __('Query') ?></th>
                                <th><?php echo __('Count') ?></th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->getNoResultSearches() as $search): ?>
                            <tr>
                                <td><?php echo $search['search'] ?></td>
                                <td><?php echo $search['count'] ?></td>
                            </tr>
                        <?php endforeach ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <?php echo __('No hits yet!'); ?>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>
