<?php /** @var $this Algolia\AlgoliaSearch\Block\Adminhtml\Analytics\Diagrams\Searches */ ?>
<?php if (count($this->getAnalytics())): ?>
<div id="algolia-analyatics-diagram"></div>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    google.charts.load('current', {packages: ['corechart', 'bar']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
        var data = new google.visualization.arrayToDataTable([
            ['Date', 'Searches', 'Users', 'No Results Rate'],
            <?php foreach ($this->getAnalytics() as $item): ?>
                ['<?php echo $item['formatted'] ?>', <?php echo $item['count'] ?>, <?php echo $item['users'] ?>, <?php echo $item['rate'] ?>],
            <?php endforeach ?>
        ]);

        var options = {
            chart: {
                subtitle: 'Searches, Users, and No Result Rates',
            },
            tooltip: {isHtml: true},
            colors: ['#5468ff', '#3a46a1', '#3ab2bd'],
            hAxis: {
                minValue: 0
            }
        };

        var chart = new google.charts.Bar(document.getElementById('algolia-analyatics-diagram'));
        chart.draw(data, google.charts.Bar.convertOptions(options));
    }
</script>
<?php else: ?>
    <div class="dashboard-diagram-nodata">
        <span><?= /* @escapeNotVerified */ __('No Data Found') ?></span>
    </div>
<?php endif ?>